### ISSUE TITLE
Nested structure: Local variable name does not match pattern

### ISSUE THREAD

**Issue by christianguenter2** [abaplint/abaplint#868] opened 2020-04-30 08:09 UTC
I have a nested structure and get 'Local variable name does not match pattern' error.

https://github.com/christianguenter2/abapGit/blob/cade5e1bf2db380f0f9dc762406ad623df112378/src/objects/zcl_abapgit_object_srvd.clas.abap#L251-L268

https://github.com/christianguenter2/abapGit/runs/632446750
![image](https://user-images.githubusercontent.com/17437789/80687407-89e90c80-8aca-11ea-85bc-e9fa6f320bfb.png)

But I don't get the error in the abaplint playground.
```REPORT zfoobar.
DATA:
  BEGIN OF ls_fields_to_clear,
    BEGIN OF content,
      source TYPE c,
    END OF content,
    BEGIN OF metadata,
      created_at      TYPE c,
      created_by      TYPE c,
      changed_at      TYPE c,
      changed_by      TYPE c,
      master_language TYPE c,
      BEGIN OF package_ref,
        name TYPE c,
      END OF package_ref,
      responsible     TYPE c,
      dt_uuid         TYPE c,
    END OF metadata,
  END OF ls_fields_to_clear.
```

What am I missing?

**Comment by larshp** [comment] 2020-04-30 08:21
probably a bug in abaplint

**Comment by larshp** [comment] 2020-04-30 14:22
did you change something? I cannot find the error in the branch, https://github.com/christianguenter2/abapGit/commits/SRVD

**Comment by christianguenter2** [comment] 2020-04-30 15:57
yeah, changed it.

**Comment by larshp** [comment] 2020-05-01 06:16
suggest closing the issue, unable to reproduce

**Comment by christianguenter2** [comment] 2020-05-01 18:52
I can reproduce it
https://github.com/christianguenter2/abapGit/tree/868
https://github.com/christianguenter2/abapGit/runs/637218759

**Comment by larshp** [comment] 2020-05-04 06:12
looks like this happens when its inside a method,

![image](https://user-images.githubusercontent.com/5888506/80940116-02a7db80-8ddf-11ea-85d0-ae8a1c2b5130.png)

**Closed** 2020-05-04 10:00 UTC
Labels: bug

**Comment by larshp** [comment] 2020-05-04 16:38
2.32.10 published
