### ISSUE TITLE
Statement does not exist in ABAPv740sp08(or a parser error), "loop"(parser_error)

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#1127] opened 2020-08-02 18:39 UTC
tested with 2.38.14

Source:
![image](https://user-images.githubusercontent.com/53995991/89129752-2672de80-d500-11ea-9dcf-3e0d99bd4719.png)

Original SAP: mv45afdb_vapma_select

**Comment by larshp** [comment] 2020-08-02 18:48
variable name `char-`

**Comment by larshp** [comment] 2020-08-08 04:59
closing root cause is https://github.com/abaplint/abaplint/issues/1116

**Closed by larshp** 2020-08-08 04:59 UTC
