### ISSUE TITLE
no_public_attributes for /bobf/cm_frw inherit class

### ISSUE THREAD

**Issue by jrodriguez-rc** [abaplint/abaplint#1042] opened 2020-07-12 11:49 UTC
I defined a new exception class inherit from /bobf/cm_frw (it has cx_dynamic_check as superclass), abaplint checks this class and raise the error no_public_attributes
![image](https://user-images.githubusercontent.com/56556686/87245470-d0050980-c445-11ea-86b3-bfc86db001a9.png)

**Comment by larshp** [comment] 2020-07-12 11:55
https://github.com/jrodriguez-rc/abap-tasks-tracker/blob/master/src/zcx_tt_management.clas.abap#L84 ?

its not inherited

**Comment by larshp** [comment] 2020-07-12 11:57
so the problem is that `/BOBF/CM_FRW` is not recognized as an exception class

**Comment by jrodriguez-rc** [comment] 2020-07-12 12:00
> so the problem is that `/BOBF/CM_FRW` is not recognized as an exception class

Exactly, `/BOBF/CM_FRW` is a class to manage messages for a BOPF and it named as CM_ instead of CX_

**Comment by larshp** [comment] 2020-07-12 17:03
plan:

A: update
https://github.com/abaplint/abaplint/blob/50aa7d6c568b47753c53482979e98771497d404d/packages/core/src/abap/types/class_definition.ts#L77
so it finds the topmost super class, if its one of the exception types the class is an exception

B: add basic version of class `/BOBF/CM_FRW` to https://github.com/abaplint/deps

**Comment by jrodriguez-rc** [comment] 2020-07-13 09:40
This is the list of BOPF exception classes in 7.50 system:
![image](https://user-images.githubusercontent.com/56556686/87288495-b8885800-c4fb-11ea-82a2-4702ae14db5a.png)

I checked some classes that begin with CM_ and all are exceptions, so updating the logic in abaplint to add this pattern could be the better option.

Using the deps repository all CM_ classes should be added to it

**Comment by larshp** [comment] 2020-07-14 05:19
well, on the long run we need to know if its a static or dynamic exception

**Comment by larshp** [comment] 2020-07-14 05:25
deps added in https://github.com/abaplint/deps/commit/93be0e49dbb6e820eee770f725e0399ed553cf28

**Comment by larshp** [comment] 2020-07-14 14:26
try again, latest version

**Comment by jrodriguez-rc** [comment] 2020-07-14 14:41
Still failing with 2.37.10
![image](https://user-images.githubusercontent.com/56556686/87439204-cb308900-c5f0-11ea-9e21-9086474d8874.png)

**Comment by larshp** [comment] 2020-07-16 13:33
fixed in 2.37.12

**Closed** 2020-07-16 13:36 UTC
