### ISSUE TITLE
Not a structure, FieldChain (check_syntax) - global table type not recognized in form

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#1523] opened 2020-11-05 09:40 UTC
abaplint 2.58.26

Issues:
```
./src/nw/#jcs#variant.fugr.#jcs#lvariantf02.abap[102, 5] - Not a structure, FieldChain (check_syntax) [E]
./src/nw/#jcs#variant.fugr.#jcs#lvariantf02.abap[103, 5] - Not a structure, FieldChain (check_syntax) [E]
./src/nw/#jcs#variant.fugr.#jcs#lvariantf02.abap[104, 5] - Not a structure, FieldChain (check_syntax) [E]
./src/nw/#jcs#variant.fugr.#jcs#lvariantf02.abap[105, 5] - Not a structure, FieldChain (check_syntax) [E]
./src/nw/#jcs#variant.fugr.#jcs#lvariantf02.abap[106, 5] - Not a structure, FieldChain (check_syntax) [E]
```
![image](https://user-images.githubusercontent.com/53995991/98223193-0ebd5300-1f52-11eb-9325-b5df1be3e3c2.png)

g_set_values is a table type.
![image](https://user-images.githubusercontent.com/53995991/98223880-04e81f80-1f53-11eb-8704-d9bd33c4af7e.png)
![image](https://user-images.githubusercontent.com/53995991/98224028-3eb92600-1f53-11eb-922f-b6f9108eafe4.png)

Putting it in playground fails due to the structure not existing.

**Comment by larshp** [comment] 2020-11-05 09:59
is `g_set_values` defined in the same program?

can you try opening the source in vscode and hover the variable? to see if its found and if found what type it has

**Comment by ed-holland** [comment] 2020-11-05 11:37
the g_set_values is defined in the top include. 

vscode has no issues with the form
![image](https://user-images.githubusercontent.com/53995991/98236420-9b244180-1f63-11eb-8caf-0b258265ef64.png)
or the definition
![image](https://user-images.githubusercontent.com/53995991/98236473-af683e80-1f63-11eb-8a6c-68386b0be263.png)

**Comment by ed-holland** [comment] 2021-01-08 14:58
Still an issue with abaplint 2.58.26

Message is the same.

**Comment by larshp** [comment] 2021-01-09 12:05
thanks, before I dig into this, can you try updating to the latest version 2.63.14 ?

**Comment by ed-holland** [comment] 2021-01-09 13:50
Looks like the abaplint/abaplint image build is stuck for a while now. Can you trigger the build again?
![image](https://user-images.githubusercontent.com/53995991/104093304-0c48e380-528a-11eb-9ca7-b464227043d2.png)

**Comment by larshp** [comment] 2021-01-09 14:02
heh, looks like github stops "inactive repos", 

![image](https://user-images.githubusercontent.com/5888506/104093586-abbaa600-528b-11eb-9240-4eed162b7921.png)

**Comment by larshp** [comment] 2021-01-09 14:43
@ed-holland try again,
![image](https://user-images.githubusercontent.com/5888506/104094468-597c8380-5291-11eb-8da9-1e165297707d.png)

**Comment by ed-holland** [comment] 2021-01-09 14:53
The bottom errors are the onces for this issue. I'll investigate the others in separate issues if required.
![image](https://user-images.githubusercontent.com/53995991/104094688-b167ba00-5292-11eb-8fc5-7184ed428adc.png)

**Comment by larshp** [comment] 2021-01-10 09:07
the dynamic calls will be fixed in #1659

**Comment by larshp** [comment] 2021-01-10 09:08
what kind of ddic thing is /JCS/BC_VARIANT_T_VALUES ? structure/database/table type?

**Comment by ed-holland** [comment] 2021-01-10 09:11
It is a table type.

**Comment by larshp** [comment] 2021-01-10 09:12
yea, I've reproduced the issue as

```abap
TYPES: BEGIN OF ty_foo,
         field TYPE string,
       END OF ty_foo.
TYPES ttyp TYPE STANDARD TABLE OF ty_foo.
DATA moo TYPE ttyp WITH HEADER LINE.

LOOP AT moo.
  WRITE moo-field.
ENDLOOP.
```

![image](https://user-images.githubusercontent.com/5888506/104118904-68fcda80-532c-11eb-8904-6b4f8d22889f.png)

**Comment by larshp** [comment] 2021-01-10 09:38
try again, 2.63.15

**Comment by ed-holland** [comment] 2021-01-10 10:07
Issue is resolved. Will check the new issues and report accordingly.
![image](https://user-images.githubusercontent.com/53995991/104120003-d95b2a00-5333-11eb-8af8-144603bce2f5.png)

Thx.

**Closed** 2021-01-10 10:07 UTC
