### ISSUE TITLE
Parser error for VALUE expression with INDEX

### ISSUE THREAD

**Issue by flaiker** [abaplint/abaplint#853] opened 2020-04-26 14:18 UTC
> Statement does not exist in ABAPv740sp08(or a parser error), "DATA" (parser_error)

```abap
DATA(lt_tab) = VALUE lty_thing_tab( FOR d IN mt_stuff INDEX INTO i
  ( id     = lv_id
    number = i
    create = /abc/cl_bc_tools=>get_create_data( ) )
).
```

**Comment by flaiker** [comment] 2020-04-26 14:27
Another more complex value expression that results in a parser error (without INDEX):

> Statement does not exist in ABAPv740sp08(or a parser error), "ls_new_item" (parser_error)

```abap
ls_new_item = VALUE #(
  item_number           = lines( rt_line_items ) + 1
  amount_dc             = /abc/cl_def_utils=>convert_amount_by_posting_key(
                            iv_amount      = lv_tax_amount_dc
                            iv_posting_key = ls_side_right-posting_key
                          )
  posting_key           = ls_side_right-posting_key
  tax_code              = is_document_data-tax_code
  tax_base_amount_dc    = - ( is_document_data-amount_dc - lv_tax_amount_dc )
  tax_condition         = COND #( WHEN lines( lt_tax_conditions ) = 1
                                  THEN lt_tax_conditions[ 1 ]-kschl )
  is_generated_tax_item = abap_true
  gl_account            = io_chart_of_accounts->get_account_for_symbol(
                            iv_symbol   = ls_side_right-account_symbol
                            iv_currency = is_document_data-document_currency
                          )
  rule                  = VALUE #( BASE CORRESPONDING #( <ls_rule> )
                                   business_transaction   = lv_transaction
                                   debit_credit_indicator = ls_side_right-debit_credit_indicator )
).
```

**Comment by flaiker** [comment] 2020-04-26 14:30
And last one (mapping with substructures):

```abap
et_errors = CORRESPONDING #( lt_errors MAPPING
  company_code    = doc-bukrs
  fiscal_year     = doc-gjahr
  document_number = doc-belnr
  msgid           = err-msgid
  msgno           = err-msgnr
  msgv1           = err-msgv1
  msgv2           = err-msgv2
  msgv3           = err-msgv3
  msgv4           = err-msgv4
).
```

**Comment by larshp** [comment] 2020-04-26 15:54
middle error caused by ` tax_base_amount_dc    = - ( is_document_data-amount_dc - lv_tax_amount_dc )` fixed in https://github.com/abaplint/abaplint/commit/40cad41f467bcf6788451ccc2a965c20f4f91d29

**Closed** 2020-04-26 15:56 UTC
