### ISSUE TITLE
Bot suggestion is wrong if inline data cannot be parsed

### ISSUE THREAD

**Issue by jan-jezek** [abaplint/abaplint#1609] opened 2020-12-10 17:24 UTC
![abap_lint_bug](https://user-images.githubusercontent.com/17530797/101807077-faeaab00-3b14-11eb-81d0-8973824b5cc0.PNG)

**Comment by larshp** [comment] 2020-12-16 08:10
closing, working as intended

**Closed by larshp** 2020-12-16 08:10 UTC
