### ISSUE TITLE
Running abaplint repeatedly can fail with an error

### ISSUE THREAD

**Issue by FreHu** [abaplint/abaplint#1646] opened 2021-01-05 14:35 UTC
Sometimes you get

```
generic[1, 1] - Error: ENOTEMPTY: directory not empty, rmdir 'C:\Users\xyz\AppData\Local\Temp\abaplint-OOSmmZ\src' at Object.rmdirSync (fs.js:850:3) (error) [E]
```

when running abaplint from cli multiple times in a row.

**Comment by FreHu** [comment] 2021-01-05 14:46
I'm using the vscode terminal on windows, nothing special. But maybe it could be the abaplint extension and cli running at the same time and interfering with each other.

What should I be recording with screentogif?

**Comment by FreHu** [comment] 2021-01-05 15:41
Not very high priority, you can just run it again

**Comment by larshp** [comment] 2021-01-09 10:15
hmm, dont really have any ideas

but try updating node?

**Comment by larshp** [comment] 2021-12-21 11:01
I cannot reproduce it, suggest closing issue

**Closed** 2021-12-22 16:12 UTC
Labels: bug
