### ISSUE TITLE
 Statement does not exist in ABAPv740sp08(or a parser error), "IF"(parser_error)

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#1128] opened 2020-08-02 18:43 UTC
tested with 2.38.14

Source:
![image](https://user-images.githubusercontent.com/53995991/89129819-d0526b00-d500-11ea-98d7-037cbbe33453.png)

Original SAP: mv45afli

**Comment by larshp** [comment] 2020-08-02 18:48
due to the variable name `CHAR-`

**Comment by larshp** [comment] 2020-08-08 04:59
closing root cause is https://github.com/abaplint/abaplint/issues/1116

**Closed by larshp** 2020-08-08 04:59 UTC
